# https://www.appveyor.com/docs/appveyor-yml/

version: 0.1.0.{build}
branches:
  only:
    - master
skip_tags: true
image: Visual Studio 2015
platform:
  - Any CPU
  - x86
  - x64
configuration:
  - Debug
  - Release
build:
  parallel: true
  project: DereTore.sln
