# https://www.appveyor.com/docs/appveyor-yml/

version: 0.2.0.{build}
branches:
  only:
    - master
skip_tags: true
image: Visual Studio 2015
platform:
  - AnyCPU
  - x86
  - x64
configuration:
  - Debug
  - Release
build:
  parallel: true
  project: DereTore.sln
environment:
  EnableNuGetPackageRestore: true
before_build:
  nuget restore
